# Generated by SylphxAI/sylphx-clients scripts/brew-formula.sh for v0.25.1.
class Sylphx < Formula
  desc "Command-line interface for the Sylphx platform"
  homepage "https://sylphx.com"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.25.1/sylphx-cli-darwin-arm64"
      sha256 "80db4dd9a7610cde490c9fe40e8509a295bd39d64ade068d815464bcef8d1210"
    end
    on_intel do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.25.1/sylphx-cli-darwin-x64"
      sha256 "afad0b3f807c9f04bb123bd38f8cecccef69017fffdeb6fea0a22dc8227da926"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.25.1/sylphx-cli-linux-arm64"
      sha256 "542eb95e970206464778ed01f1f9020260528091c36b1b66df5b839a93ebfe51"
    end
    on_intel do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.25.1/sylphx-cli-linux-x64"
      sha256 "4da7228eac5d91eff39318d6ef5edc2a5e9e1ffcd25714a3bd4f6d35fa5c3419"
    end
  end

  def install
    bin.install Dir["sylphx-cli-*"].first => "sylphx"
  end

  test do
    assert_equal "sylphx #{version}", shell_output("#{bin}/sylphx --version").strip
  end
end
