# Generated by SylphxAI/sylphx-clients scripts/brew-formula.sh for v0.24.1.
class Sylphx < Formula
  desc "Command-line interface for the Sylphx platform"
  homepage "https://sylphx.com"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.24.1/sylphx-cli-darwin-arm64"
      sha256 "ee66ad711983b46a25a3b6ec6c9dd9a2177890ce8da8938bc2d1151e71285ece"
    end
    on_intel do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.24.1/sylphx-cli-darwin-x64"
      sha256 "ac654439021a06210cd752e2a4c4ec7bc999a67eb5171a29c09182a26dee03cc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.24.1/sylphx-cli-linux-arm64"
      sha256 "9e7394dc7d2f3f30a91408b692a90bdaeda2be2ec2e6d1baa763a0bf8a027240"
    end
    on_intel do
      url "https://github.com/SylphxAI/sylphx-clients/releases/download/v0.24.1/sylphx-cli-linux-x64"
      sha256 "9a496e2d5026e2d55fb8cc9f0811057c5d8ac2463aad7bf7e89c5407accb97be"
    end
  end

  def install
    bin.install Dir["sylphx-cli-*"].first => "sylphx"
  end

  test do
    assert_equal "sylphx #{version}", shell_output("#{bin}/sylphx --version").strip
  end
end
